"""Add timestamp column

Revision ID: 70258089e5b3
Revises: da868e7d2172
Create Date: 2023-06-22 04:47:48.719949

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70258089e5b3"
down_revision = "da868e7d2172"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "indicator_period", sa.Column("timestamp", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indicator_period", "timestamp")
    # ### end Alembic commands ###
