"""Add kpi values table

Revision ID: da868e7d2172
Revises: b671607f133b
Create Date: 2023-06-15 11:04:12.341588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da868e7d2172"
down_revision = "b671607f133b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kpi_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kpi")),
        sa.UniqueConstraint("kpi_id", "period", name=op.f("uq_kpi_kpi_id")),
    )
    op.create_index(op.f("ix_kpi_kpi_id"), "kpi", ["kpi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kpi_kpi_id"), table_name="kpi")
    op.drop_table("kpi")
    # ### end Alembic commands ###
